// File generated by FlutterFire CLI (stub — grava-35d5.9).
//
// This is a hand-written stub that mirrors the shape of the file produced by
// `flutterfire configure` so that `main.dart` can call:
//
//   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)
//
// without a compile error before a real Firebase project exists.
//
// Once the real Firebase project exists, run:
//   flutterfire configure --project=<sportbuddies-project-id>
// which will overwrite this file with the canonical generated form containing
// real platform-specific options.
//
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _placeholder;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _placeholder;
      case TargetPlatform.iOS:
        return _placeholder;
      case TargetPlatform.macOS:
        return _placeholder;
      default:
        return _placeholder;
    }
  }

  /// Stub placeholder — all fields are TODO values.
  ///
  /// Replace with real values once the Firebase project is configured via
  /// `flutterfire configure`.
  static const FirebaseOptions _placeholder = FirebaseOptions(
    apiKey: 'TODO-firebase-api-key',
    appId: 'TODO-firebase-app-id',
    messagingSenderId: 'TODO-firebase-sender-id',
    projectId: 'TODO-firebase-project-id',
    storageBucket: 'TODO-firebase-storage-bucket',
    authDomain: 'TODO-firebase-auth-domain',
  );
}
